### ISSUE TITLE
Question about Additional Entity Attributes

### ISSUE THREAD

**Issue by Irrational7615** [DaFuqs/AdditionalEntityAttributes#21]
About this one:
BONUS_RARE_LOOT_ROLLS: The number of times the chance-based loot table is rolled.
It accepts a float in the value. How does that work if it does? (Sorry I'm opening this as an issue, I didn't see anywhere else I could put it)

**Comment by DaFuqs** [comment]
If a loot table condition evaluated to false and would not have dropped (Like Iron from a Zombie, since that has a ~1% chance): A value of 1.0 will result in 1 additional roll with the original chance. So if a drop has a 10% chance:
- `BONUS_RARE_LOOT_ROLLS=1.0` will roll another time with 10% chance
- `BONUS_RARE_LOOT_ROLLS = 2.0` will result in another roll with 20% chance
- `BONUS_RARE_LOOT_ROLLS = 0.5` will result in another roll with 5% chance

**Comment by Irrational7615** [comment]
Thanks! That’s an interesting way of doing it, I assumed each one would be an extra roll, not one roll with modified/extra chance.

**Comment by softyydev** [comment]
if you don't mind answering this too, what exactly do the values for bonus_loot_count_rolls work? my assumption originally was that it was more drops like rotten flesh but that's not how it worked in my tests

**Comment by Irrational7615** [comment]
Some mobs have rare drops. Zombies have a small chance to drop a carrot, potato or iron ingot, and wither skeletons their head. These drops are what the rolls affect.

Edit: that’s what the rare loot rolls one does. I can test that one and get back to you, but if you couldn’t find out what it does then I doubt I will. In the description it says it modifies how looting affects drops.

**Comment by softyydev** [comment]
i didn't notice a difference between the two value but i might've set the values wayyy to high so if you do find the difference lmk

**Comment by Irrational7615** [comment]
I had a test and the bonus loot count tools doesn’t seem to work for me at least. I observed no difference in drops when I had it set to 128 to when not with and without the looting enchantment.
