### ISSUE TITLE
[Crash] Skeleton doesn't have `additionalentityattributes:player.critical_bonus_damage`

### ISSUE THREAD

**Issue by Phoupraw** [DaFuqs/AdditionalEntityAttributes#28]
[crash-2024-02-19_22.28.47-server.txt](https://github.com/DaFuqs/AdditionalEntityAttributes/files/14332332/crash-2024-02-19_22.28.47-server.txt)
[latest.log](https://github.com/DaFuqs/AdditionalEntityAttributes/files/14332336/latest.log)

This crash is because my mod includes additionalentityattributes 1.7.0+1.20.0 while zenith includes additionalentityattributes 1.4.0+1.20.0.

Why can't mobs have critical bonus damage?

**Comment by Globox1997** [comment]
L2327: `Caused by: java.lang.IllegalArgumentException: Can't find attribute additionalentityattributes:player.critical_bonus_damage`

Interesting lines L2332-2334:
```
	at dev.shadowsoffire.attributeslib.impl.AttributeEvents.lambda$apothCriticalStrike$3(AttributeEvents.java:200) ~[zenith_attributes-0.1.5.jar:?]
	at io.github.fabricators_of_create.porting_lib.entity.events.living.LivingEntityDamageEvents.lambda$static$0(LivingEntityDamageEvents.java:15) ~[porting_lib_entity-2.1.1127+1.20-fb24e5b47219a943.jar:?]
	at net.minecraft.class_1309.handler$fep000$porting_lib_entity$fireHurtEvent(class_1309.java:22823) ~[client-intermediary.jar:?]
```

**Comment by DaFuqs** [comment]
The relevant lines in Zenith-Attribs:
https://github.com/TheWinABagel/ZenithAttributes/blob/d127b6efe640b59473f0d10b3e3a29c3437258f1/src/main/java/dev/shadowsoffire/attributeslib/impl/AttributeEvents.java#L194

Zenith does not check the existence of the attribute, but always accesses it for all living entities.
Given that the attribute was always present on all LivingEntities this was no issue at all.

> Why can't mobs have critical bonus damage?

Critical Damage is only dealt by players [under certain conditions](https://minecraft.wiki/w/Damage#Critical_hit) and [AEA only ever evaluated the attribute for players](https://github.com/DaFuqs/AdditionalEntityAttributes/blob/1c6cb03cd3b2a2195f8d9274d885cb721d3362a9/src/main/java/de/dafuqs/additionalentityattributes/mixin/common/PlayerEntityMixin.java#L39). As such, adding the attribute to non-players always was pretty much an oversight on AEAs part, that has since been corrected.

Ideally Zenith updates to use the new version of AEA and checks for players, or better if the entity has that attibute (in case mods add that attribute to their own mobs). In the meantime, you are safe using the previous version of AEA, unless you want to use the attribute that was added with last update.

I'll let Bagel know!

**Comment by DaFuqs** [comment]
Zenith fixed that one.
